apiVersion: apps/v1
kind: Deployment
metadata:
  name: <+service.name>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <+service.name>
  template:
    metadata:
      labels:
        app: <+service.name>
    spec:
      containers:
        - name: <+service.name>
          image: <+artifacts.primary.imagePath>:<+artifacts.primary.tag>
          ports:
            - containerPort: 8080