apiVersion: v1
kind: Service
metadata:
  name: <+service.name>-service
spec:
  selector:
    app: <+service.name>
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer